name: Deploy Environment 

on: 
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Environment
        options: 
        - dev 
        - qa
        - staging
        - prod
      instance:
        description: 'Optional unique instance in an environment'
        default: ''
        required: false
        type: string

jobs:
  containerized_job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/miruken-go/demo.microservice.deployment:1686001494
      env:
        tenantId:                       ${{ variables.TENANT_ID }}
        subscriptionId:                 ${{ variables.SUBSCRIPTION_ID }}
        deploymentPipelineClientId:     ${{ variables.DEPLOYMENT_PIPELINE_CLIENT_ID }}
        deploymentPipelineClientSecret: ${{ secrets.DEPLOYMENT_PIPELINE_CLIENT_SECRET }}
        env:                            ${{ inputs.env }}
        instance:                       ${{ inputs.instance }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: deployEnvironment
      run:  node ./src/deployEnvironment.js 
